// <auto-generated />
using System;
using Exercise03ex01.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Exercise03ex01.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230801090007_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Exercise03ex01.Models.Printer", b =>
                {
                    b.Property<int>("engenPrintersID")
                        .HasColumnType("int");

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("createTimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("fileOutput")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("folderToMonitor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("outputType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("printerMake")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("printerName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("engenPrintersID");

                    b.ToTable("Printers", (string)null);
                });

            modelBuilder.Entity("Exercise03ex01.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("firstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("User2", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
